<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ANSHULs-MacBook-Pro.local" failures="1" tests="2" name="Test" time="44.565" errors="0" timestamp="2023-04-29T23:33:25 IST">
  <testcase classname="testcases.verifylogin" name="login" time="13.609">
    <failure type="java.lang.AssertionError" message="Please check your username and password. If you still can&amp;apos;t log in, contact your Salesforce administrator. expected:&amp;lt;Please check your username and password. If you still can&amp;apos;t log in, contact your Salesforce administrator.&amp;gt; but was:&amp;lt;Error message is not valid&amp;gt;">
      <![CDATA[java.lang.AssertionError: Please check your username and password. If you still can't log in, contact your Salesforce administrator. expected:<Please check your username and password. If you still can't log in, contact your Salesforce administrator.> but was:<Error message is not valid>
at testcases.verifylogin.login(verifylogin.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="testcases.verifysignup" name="signup" time="16.163"/>
</testsuite> <!-- Test -->
